/**
 * Publishes `out/` to the GitHub Pages user site.
 *
 * WHY THE USER SITE RATHER THAN A PROJECT PAGE
 * --------------------------------------------
 * A project page is served from `/<repo>/`, which means every absolute asset
 * path in the app — the MapLibre worker at `/maplibre/…`, the photography at
 * `/images/bali/…` — would need a basePath prefix. The user site
 * (`<account>.github.io`) is served from the domain root, so nothing has to be
 * rewritten and there is no class of bug where a path works locally and 404s
 * in production.
 *
 * `.nojekyll` is not optional: GitHub Pages runs Jekyll by default, and Jekyll
 * silently drops any directory beginning with an underscore — which is exactly
 * where Next.js puts every chunk and stylesheet. Without it the site loads a
 * blank page.
 *
 * Usage: node scripts/build-static.mjs && node scripts/publish-pages.mjs
 */

import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const OUT = join(ROOT, 'out');
const STAGE = join(ROOT, '.pages-stage');
const REPO = `${process.env.GH_ACCOUNT ?? 'suiwenke69-cyber'}.github.io`;
const ACCOUNT = process.env.GH_ACCOUNT ?? 'suiwenke69-cyber';

if (!existsSync(OUT)) {
  console.error('out/ does not exist. Run `node scripts/build-static.mjs` first.');
  process.exit(1);
}

const run = (cmd, args, cwd = ROOT) =>
  execFileSync(cmd, args, { cwd, stdio: 'inherit', env: process.env });

console.log('▶ Staging the export');
rmSync(STAGE, { recursive: true, force: true });
mkdirSync(STAGE, { recursive: true });
cpSync(OUT, STAGE, { recursive: true });

// Jekyll must not touch this. See the header comment.
writeFileSync(join(STAGE, '.nojekyll'), '');
console.log('   .nojekyll written');

console.log('▶ Initialising the pages repository');
run('git', ['init', '-q'], STAGE);
run('git', ['config', 'user.name', ACCOUNT], STAGE);
run('git', ['config', 'user.email', `${ACCOUNT}@users.noreply.github.com`], STAGE);
run('git', ['checkout', '-q', '-b', 'main'], STAGE);
run('git', ['add', '-A'], STAGE);
run(
  'git',
  ['commit', '-q', '-m', 'Publish Meridian static build\n\nGenerated by scripts/build-static.mjs from the source repository.'],
  STAGE,
);

console.log(`▶ Pushing to ${ACCOUNT}/${REPO}`);
let exists = true;
try {
  execFileSync('gh', ['repo', 'view', `${ACCOUNT}/${REPO}`], { stdio: 'ignore' });
} catch {
  exists = false;
}

if (!exists) {
  run('gh', ['repo', 'create', REPO, '--public', '--description', 'Meridian — static build of the map-first Southeast Asia travel planner'], STAGE);
}

run('git', ['remote', 'add', 'origin', `https://github.com/${ACCOUNT}/${REPO}.git`], STAGE);
run('git', ['push', '-q', '-f', '-u', 'origin', 'main'], STAGE);

console.log('▶ Asking GitHub to serve Pages from main /');
try {
  execFileSync(
    'gh',
    ['api', '-X', 'POST', `repos/${ACCOUNT}/${REPO}/pages`, '-f', 'source[branch]=main', '-f', 'source[path]=/'],
    { stdio: 'inherit' },
  );
} catch {
  // Already configured is the normal case on a re-publish.
  execFileSync(
    'gh',
    ['api', '-X', 'PUT', `repos/${ACCOUNT}/${REPO}/pages`, '-f', 'source[branch]=main', '-f', 'source[path]=/'],
    { stdio: 'inherit' },
  );
}

rmSync(STAGE, { recursive: true, force: true });
console.log(`\n✅ published — https://${REPO}/`);
console.log('   GitHub takes a minute or two to build and deploy on first publish.');
